sudo: required
dist: trusty

language: node_js
node_js:
  - "lts/*"
cache: yarn
env:
  global:
    - SOURCE_DIR="build"
    - DESTINATION_PATH="https://blobforsite.blob.core.windows.net/blobcontainer"
    - CDN_RESOURCE_GROUP="gl_syncweek"
    - CDN_ENDPOINT_NAME="iotgeneratorweb"
    - CDN_PROFILE="iotpage"

stages:
  - test
  - name: deploy
    if: branch = dev

jobs: 
  include:
    - stage: test
      script:
      - yarn test
      - yarn build
    - stage: deploy
      script:
      # installig azure-cli=2.0.38 >
      # https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
      - AZ_REPO=$(lsb_release -cs)
      - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list  
      - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      - sudo apt-get install apt-transport-https
      - sudo apt-get update && sudo apt-get install azure-cli=2.0.38-1~trusty
      # installing AzCopy=7.2.0 https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux?toc=%2fazure%2fstorage%2fblobs%2ftoc.json
      - sudo echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty main" > azure.list
      - sudo cp ./azure.list /etc/apt/sources.list.d/
      - sudo apt-get update
      - sudo apt-get install azcopy=7.2.0-netcore
      - yarn build
      - azcopy --source $SOURCE_DIR --destination $DESTINATION_PATH --dest-key $AZURE_STORAGE_ACCESS_KEY --recursive --quiet --set-content-type
      - az login --service-principal -u $SP_NAME --password $SP_PASSWORD --tenant $SP_TENANT 
      - az cdn endpoint purge -g $CDN_RESOURCE_GROUP -n $CDN_ENDPOINT_NAME --profile-name $CDN_PROFILE --content-paths "/*"
